# Generated by Django 4.2.5 on 2023-09-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0002_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField()),
                ('idCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RentApp.clientes')),
                ('idVehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RentApp.vehiculos')),
            ],
        ),
    ]
