# Generated by Django 4.2.5 on 2023-09-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0003_arriendos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='cantidad',
        ),
    ]
