# Generated by Django 4.2.5 on 2023-09-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0004_remove_vehiculos_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='arrendado',
            field=models.BooleanField(default=False),
        ),
    ]
