# Generated by Django 4.2.5 on 2023-09-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0005_vehiculos_arrendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='tipo',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Moto', 'Moto')], max_length=4),
        ),
    ]
