# Generated by Django 4.2.5 on 2023-09-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0006_alter_vehiculos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='tipo',
            field=models.CharField(max_length=4),
        ),
    ]
